// DirectX9 Hook by AnthIste and illuz1oN (C) 2010,
// Contact us at illuz1oN@hotmail.co.uk or anthiste.anthiste@gmail.com,
// Thanks to Echo and others for advice.
//
// Built with Visual Studio 2008.
//
// p.s. Node is sexy ^_^.

#ifndef __DIRECTX9_VTABLE
#define __DIRECTX9_VTABLE

#define DX9_QUERYINTERFACE 0
#define DX9_ADDREF 1
#define DX9_RELEASE 2
#define DX9_TESTCOOPERATIVELEVEL 3
#define DX9_GETAVAILABLETEXTUREMEM 4
#define DX9_EVICTMANAGEDRESOURCES 5
#define DX9_GETDIRECT3D 6
#define DX9_GETDEVICECAPS 7
#define DX9_GETDISPLAYMODE 8
#define DX9_GETCREATIONPARAMETERS 9
#define DX9_SETCURSORPROPERTIES 10
#define DX9_SETCURSORPOSITION 11
#define DX9_SHOWCURSOR 12
#define DX9_CREATEADDITIONALSWAPCHAIN 13
#define DX9_GETSWAPCHAIN 14
#define DX9_GETNUMBEROFSWAPCHAINS 15
#define DX9_RESET 16
#define DX9_PRESENT 17
#define DX9_GETBACKBUFFER 18
#define DX9_GETRASTERSTATUS 19
#define DX9_SETDIALOGBOXMODE 20
#define DX9_SETGAMMARAMP 21
#define DX9_GETGAMMARAMP 22
#define DX9_CREATETEXTURE 23
#define DX9_CREATEVOLUMETEXTURE 24
#define DX9_CREATECUBETEXTURE 25
#define DX9_CREATEVERTEXBUFFER 26
#define DX9_CREATEINDEXBUFFER 27
#define DX9_CREATERENDERTARGET 28
#define DX9_CREATEDEPTHSTENCILSURFACE 29
#define DX9_UPDATESURFACE 30
#define DX9_UPDATETEXTURE 31
#define DX9_GETRENDERTARGETDATA 32
#define DX9_GETFRONTBUFFERDATA 33
#define DX9_STRETCHRECT 34
#define DX9_COLORFILL 35
#define DX9_CREATEOFFSCREENPLAINSURFACE 36
#define DX9_SETRENDERTARGET 37
#define DX9_GETRENDERTARGET 38
#define DX9_SETDEPTHSTENCILSURFACE 39
#define DX9_GETDEPTHSTENCILSURFACE 40
#define DX9_BEGINSCENE 41
#define DX9_ENDSCENE 42
#define DX9_CLEAR 43
#define DX9_SETTRANSFORM 44
#define DX9_GETTRANSFORM 45
#define DX9_MULTIPLYTRANSFORM 46
#define DX9_SETVIEWPORT 47
#define DX9_GETVIEWPORT 48
#define DX9_SETMATERIAL 49
#define DX9_GETMATERIAL 50
#define DX9_SETLIGHT 51
#define DX9_GETLIGHT 52
#define DX9_LIGHTENABLE 53
#define DX9_GETLIGHTENABLE 54
#define DX9_SETCLIPPLANE 55
#define DX9_GETCLIPPLANE 56
#define DX9_SETRENDERSTATE 57
#define DX9_GETRENDERSTATE 58
#define DX9_CREATESTATEBLOCK 59
#define DX9_BEGINSTATEBLOCK 60
#define DX9_ENDSTATEBLOCK 61
#define DX9_SETCLIPSTATUS 62
#define DX9_GETCLIPSTATUS 63
#define DX9_GETTEXTURE 64
#define DX9_SETTEXTURE 65
#define DX9_GETTEXTURESTAGESTATE 66
#define DX9_SETTEXTURESTAGESTATE 67
#define DX9_GETSAMPLERSTATE 68
#define DX9_SETSAMPLERSTATE 69
#define DX9_VALIDATEDEVICE 70
#define DX9_SETPALETTEENTRIES 71
#define DX9_GETPALETTEENTRIES 72
#define DX9_SETCURRENTTEXTUREPALETTE 73
#define DX9_GETCURRENTTEXTUREPALETTE 74
#define DX9_SETSCISSORRECT 75
#define DX9_GETSCISSORRECT 76
#define DX9_SETSOFTWAREVERTEXPROCESSING 77
#define DX9_GETSOFTWAREVERTEXPROCESSING 78
#define DX9_SETNPATCHMODE 79
#define DX9_GETNPATCHMODE 80
#define DX9_DRAWPRIMITIVE 81
#define DX9_DRAWINDEXEDPRIMITIVE 82
#define DX9_DRAWPRIMITIVEUP 83
#define DX9_DRAWINDEXEDPRIMITIVEUP 84
#define DX9_PROCESSVERTICES 85
#define DX9_CREATEVERTEXDECLARATION 86
#define DX9_SETVERTEXDECLARATION 87
#define DX9_GETVERTEXDECLARATION 88
#define DX9_SETFVF 89
#define DX9_GETFVF 90
#define DX9_CREATEVERTEXSHADER 91
#define DX9_SETVERTEXSHADER 92
#define DX9_GETVERTEXSHADER 93
#define DX9_SETVERTEXSHADERCONSTANTF 94
#define DX9_GETVERTEXSHADERCONSTANTF 95
#define DX9_SETVERTEXSHADERCONSTANTI 96
#define DX9_GETVERTEXSHADERCONSTANTI 97
#define DX9_SETVERTEXSHADERCONSTANTB 98
#define DX9_GETVERTEXSHADERCONSTANTB 99
#define DX9_SETSTREAMSOURCE 100
#define DX9_GETSTREAMSOURCE 101
#define DX9_SETSTREAMSOURCEFREQ 102
#define DX9_GETSTREAMSOURCEFREQ 103
#define DX9_SETINDICES 104
#define DX9_GETINDICES 105
#define DX9_CREATEPIXELSHADER 106
#define DX9_SETPIXELSHADER 107
#define DX9_GETPIXELSHADER 108
#define DX9_SETPIXELSHADERCONSTANTF 109
#define DX9_GETPIXELSHADERCONSTANTF 110
#define DX9_SETPIXELSHADERCONSTANTI 111
#define DX9_GETPIXELSHADERCONSTANTI 112
#define DX9_SETPIXELSHADERCONSTANTB 113
#define DX9_GETPIXELSHADERCONSTANTB 114
#define DX9_DRAWRECTPATCH 115
#define DX9_DRAWTRIPATCH 116
#define DX9_DELETEPATCH 117
#define DX9_CREATEQUERY 118

#endif