// DirectX9 Hook by AnthIste and illuz1oN (C) 2010,
// Contact us at illuz1oN@hotmail.co.uk or
// anthiste.anthiste@gmail.com,
// Thanks to Echo and others for advice.
//
// p.s. Node is sexy ^_^.

#ifndef __DIRECTX9_VTABLE
#define __DIRECTX9_VTABLE

namespace DirectX9Hook {

enum {
	QUERYINTERFACE, ADDREF, RELEASE, TESTCOOPERATIVELEVEL,
	GETAVAILABLETEXTUREMEM, EVICTMANAGEDRESOURCES, GETDIRECT3D,
	GETDEVICECAPS, GETDISPLAYMODE, GETCREATIONPARAMETERS, SETCURSORPROPERTIES,
	SETCURSORPOSITION, SHOWCURSOR, CREATEADDITIONALSWAPCHAIN, GETSWAPCHAIN,
	GETNUMBEROFSWAPCHAINS,RESET, PRESENT, GETBACKBUFFER, GETRASTERSTATUS,
	SETDIALOGBOXMODE, SETGAMMARAMP, GETGAMMARAMP, CREATETEXTURE, 
	CREATEVOLUMETEXTURE, CREATECUBETEXTURE, CREATEVERTEXBUFFER, CREATEINDEXBUFFER,
	CREATERENDERTARGET, CREATEDEPTHSTENCILSURFACE, UPDATESURFACE, UPDATETEXTURE,
	GETRENDERTARGETDATA, GETFRONTBUFFERDATA, STRETCHRECT, COLORFILL, CREATEOFFSCREENPLAINSURFACE,
	SETRENDERTARGET, GETRENDERTARGET, SETDEPTHSTENCILSURFACE, GETDEPTHSTENCILSURFACE,
	BEGINSCENE, ENDSCENE, CLEAR, SETTRANSFORM, GETTRANSFORM, MULTIPLYTRANSFORM, SETVIEWPORT,
	GETVIEWPORT, SETMATERIAL, GETMATERIAL,  SETLIGHT, GETLIGHT, LIGHTENABLE, GETLIGHTENABLE,
	SETCLIPPLANE, GETCLIPPLANE, SETRENDERSTATE, GETRENDERSTATE, CREATESTATEBLOCK, BEGINSTATEBLOCK,
	ENDSTATEBLOCK, SETCLIPSTATUS, GETCLIPSTATUS, GETTEXTURE, SETTEXTURE, GETTEXTURESTAGESTATE, 
	SETTEXTURESTAGESTATE, GETSAMPLERSTATE, SETSAMPLERSTATE, VALIDATEDEVICE, SETPALETTEENTRIES,
	GETPALETTEENTRIES, SETCURRENTTEXTUREPALETTE, GETCURRENTTEXTUREPALETTE, SETSCISSORRECT, 
	GETSCISSORRECT, SETSOFTWAREVERTEXPROCESSING, GETSOFTWAREVERTEXPROCESSING, SETNPATCHMODE,
	GETNPATCHMODE, DRAWPRIMITIVE, DRAWINDEXEDPRIMITIVE, DRAWPRIMITIVEUP, DRAWINDEXEDPRIMITIVEUP,
	PROCESSVERTICES, CREATEVERTEXDECLARATION, SETVERTEXDECLARATION, GETVERTEXDECLARATION, SETFVF,
	GETFVF, CREATEVERTEXSHADER, SETVERTEXSHADER, GETVERTEXSHADER, SETVERTEXSHADERCONSTANTF,
	GETVERTEXSHADERCONSTANTF, SETVERTEXSHADERCONSTANTI, GETVERTEXSHADERCONSTANTI, SETVERTEXSHADERCONSTANTB,
	GETVERTEXSHADERCONSTANTB, SETSTREAMSOURCE, GETSTREAMSOURCE, SETSTREAMSOURCEFREQ, GETSTREAMSOURCEFREQ,
	SETINDICES, GETINDICES, CREATEPIXELSHADER, SETPIXELSHADER, GETPIXELSHADER, SETPIXELSHADERCONSTANTF,
	GETPIXELSHADERCONSTANTF, SETPIXELSHADERCONSTANTI, GETPIXELSHADERCONSTANTI, SETPIXELSHADERCONSTANTB,
	GETPIXELSHADERCONSTANTB, DRAWRECTPATCH, DRAWTRIPATCH, DELETEPATCH, CREATEQUERY
};

}

#endif